// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw60wuBj8PC8EkKSjA31AQy3qKXfE6aZE',
    appId: '1:541129338106:web:53a4b45902c4c24743ed43',
    messagingSenderId: '541129338106',
    projectId: 'tripbudgeter-c3bac',
    authDomain: 'tripbudgeter-c3bac.firebaseapp.com',
    storageBucket: 'tripbudgeter-c3bac.firebasestorage.app',
    measurementId: 'G-JNNEG7PNY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyDqVCHt-iFe1ZLra6KztMUTmL-7pR3uo',
    appId: '1:541129338106:android:493cb73f9096e2ea43ed43',
    messagingSenderId: '541129338106',
    projectId: 'tripbudgeter-c3bac',
    storageBucket: 'tripbudgeter-c3bac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqK2B7epY1eYziBStXPM393rtkeSkvNk4',
    appId: '1:541129338106:ios:a92cb30c1498782743ed43',
    messagingSenderId: '541129338106',
    projectId: 'tripbudgeter-c3bac',
    storageBucket: 'tripbudgeter-c3bac.firebasestorage.app',
    iosBundleId: 'com.example.tripBudgeter',
  );
}
